name: Actions Runner Controller Demo
on:
  workflow_dispatch:
  push:
    branches: [main]
run-name: ${{github.event_name}} triggers Running
jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"

  workflow-command-job:
    env:
      JOB_ENV_SEC: ${{secrets.DEV_SEC}}
    runs-on: arc-runner-set
    steps: 
    - name: Disable workflow commands
      run: |
        echo '::warning:: This is a warning message, to demonstrate that commands are being processed.'
        stopMarker=IAMSTOPMARKER_${RANDOM}_${RANDOM}
        echo "::stop-commands::$stopMarker"
        echo '::warning:: This will NOT be rendered as a warning, because stop-commands has been invoked.'
        echo "::$stopMarker::"
        echo '::warning:: This is a warning again, because stop-commands has been turned off.'
    - name: Notice command
      env:
        ENV_SEC: ${{secrets.DEV_SEC}}
      run: |
        echo "::notice file=README.md,line=20,endline=30,title=See Readme::Pay attention plase"
        echo "::group::Notice"
        echo Hellowood
        env
        echo var ENV_SEC: $ENV_SEC
        echo sec ENV_SEC: ${{secrets.DEV_SEC}}
        echo "Good afternoon"
        echo "Happy Thursday"
        echo "::endgroup::"
    - name: I am Dev
      if: ${{env.JOB_ENV_SEC == 'dev'}}
      run: echo DEV_SEC is dev
    - name: I am repo
      if: ${{env.JOB_ENV_SEC == 'repo'}}
      run: echo DEV_SEC is repo