name: Actions Runner Controller Demo
on:
  workflow_dispatch:
  push:
    branches: [main]
run-name: ${{github.event_name}} triggers Running
jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    outputs:
      outExp1: ${{job.status }}

  workflow-command-job:
    needs: Explore-GitHub-Actions
    environment: dev
    env:
      JOB_ENV_SEC: ${{secrets.DEV_SEC}}
      JOB_STATUS: ${{needs.Explore-GitHub-Actions.outputs.outExp1}}
    runs-on: arc-runner-set
    steps: 
    - name: Disable workflow commands
      run: |
        echo '::warning:: This is a warning message, to demonstrate that commands are being processed.'
        stopMarker=IAMSTOPMARKER_${RANDOM}_${RANDOM}
        echo "::stop-commands::$stopMarker"
        echo '::warning:: This will NOT be rendered as a warning, because stop-commands has been invoked.'
        echo "::$stopMarker::"
        echo '::warning:: This is a warning again, because stop-commands has been turned off.'
    - name: Notice command
      env:
        ENV_SEC: ${{secrets.DEV_SEC}}
      shell: bash
      run: |
        echo "::notice file=README.md,line=20,endline=30,title=See Readme::Pay attention plase"
        echo "::group::Notice"
        echo Hellowood
        echo Last job status: $JOB_STATUS
        echo lowcase of var ENV_SEC: ${ENV_SEC,,}
        echo upcase of var ENV_SEC: ${ENV_SEC^^}
        echo sec ENV_SEC: ${{secrets.DEV_SEC}}
        echo "Good afternoon"
        echo "Happy Thursday"
        echo "variable : $DEV_SCHOOL"
        echo "variable: ${{vars.ETHAN_HOME}}"
        echo "variable: ${{vars.DEV_SCHOOL}}"
        env
        echo "::endgroup::"
    - name: I am Dev
      if: ${{env.JOB_ENV_SEC == 'dev'}}
      run: echo DEV_SEC is dev
    - name: I am Repo
      if: ${{env.JOB_ENV_SEC == 'repo'}}
      run: echo DEV_SEC is repo
  calling-job:
    uses: ./.github/workflows/call-me.yaml
    with:
      var1: Sunday is today
      var2: What is tomorrow
    secrets:
      pat1: ${{secrets.GITHUB_TOKEN}}