name: Hourly Schedule
run-name: ${{github.actor}} is running Hourly Scheduled Workflow
on:
  schedule:
  - cron: '40 */12 * * *'

jobs:
  Say-Good-Night:
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      id: step-1
      run: |
        echo Good Night
        echo "month=May" >> $GITHUB_OUTPUT
    - name: step 2
      run: |
        echo Output of Step 1 is ${{steps.step-1.outputs.month}}

