---
name: Release Workflow
run-name: ${{github.action}} trigers Release Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  release-job:
    runs-on: arc-runner-set
    permissions:
      contents: write
    name: Release Version Job
    steps:
      - uses: actions/checkout@v4
      - name: Create release step
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{inputs.version}}
          release_name: Release ${{inputs.version}}


