---
name: Release Workflow
run-name: ${{github.action}} trigers Release Workflow
on:
  release:
    types:
    - created
    - edited
    - released

jobs:
  rel-job:
    runs-on:
      labels: [self-hosted, Linux]
    steps:
    - name: Step one
      run: |
        echo $GITHUB_REF_NAME is ${{ github.event_name }} by ${{github.actor}}
