---
name: simple-flow
run-name: Simple flow is triggered by ${{ github.event_name }}
on:
    push:
      branches: main
      paths-ignore:
      - '**/hourly.yaml'
      - '**/release.yml'
      - '**/arc-run-wfl.yaml'
    workflow_dispatch:
    
jobs:
  say-hello:
    runs-on: arc-runner-set
    name: Hello Belly
    environment: dev
    steps:
    - name: Generate artifact
      run: |
        echo "Hello, World" >> artifact.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: artifact.txt
        name: myart
    - name: Speak
      run: |
        echo "Hello, World"
        echo Welcome to my world.
  say-goodbye:
    strategy:
      matrix:
        lane: [one, two]
        month: [May, June]
    name: Good Bye
    runs-on: arc-runner-set
    steps:
    - name: Speak
      run: |
        echo "Good Bye, Ethan! It is lane: ${{matrix.lane}}, month: ${{matrix.month}}"
        echo "Good night, Ethan!"
  close:
    name: Close it
    runs-on: arc-runner-set
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: myart
    - name: Close
      run: |
        echo "I'm done"
        cat artifact.txt
    needs: 
     - say-goodbye
     - say-hello

